name: Pull request check
on:
  pull_request:
    types: [opened, reopened, workflow_dispatch]
jobs:
  nameHere:
    runs-on: ubuntu-latest
    steps:
        - name: Get image
          run: docker pull godlikeprofi/nodevite
          continue-on-error: true
        - name: Run image
          run: docker run -p 8000:8888 godlikeprofi/nodevite
        - name: echo 
          run: echo "qwerty"
        #docker pull docker.HOSTNAME/OWNER/REPOSITORY/IMAGE_NAME:TAG_NAME 