name: Pull request check
on:
  pull_request:
    types: [opened, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test          
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: create comment
      - uses: actions/github-script@v6
        id: set-result
        with:
          github-token: $ {{ secrets.MY_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}" #comment
